### ISSUE TITLE
Shrink images used for background images

### ISSUE THREAD

**Issue by samccone** [kevinwuhoo/ui-styleguides#1]
Currently they are massive, and you are taking a large perf hit each time one is painted.

**Comment by samccone** [comment]
xref #2 

![screen shot 2015-06-26 at 11 55 02 am](https://cloud.githubusercontent.com/assets/883126/8385139/dc8e9f02-1bfa-11e5-81be-53ee6d626967.png)

:scream:

**Comment by kevinwuhoo** [comment]
![](http://media.giphy.com/media/q9fohf0Erd50A/giphy.gif)
